services:

    api-gateway:
        container_name: api-gateway-service
        image: demo/api-gateway
        build:
            context: .
            dockerfile: gateways/ApiGateway/Dockerfile
        ports:
            - "27026:8080"
            - "28026:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: on-failure
        networks:
            demo-network:
                ipv4_address: 172.25.10.10
        depends_on:
            - tmdb-collector   

    tmdb-collector:
        container_name: api-tmdb-collector
        image: demo/tmdb-collector
        build:
            context: .
            dockerfile: apis/TmdbCollectorApi/Dockerfile
        ports:
            - "27025:8080"
            - "28025:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: on-failure
        networks:
            demo-network:
                ipv4_address: 172.25.10.11

networks:
    demo-network:
        ipam:
            config:
              - subnet: "172.25.10.0/24"
                gateway: "172.25.10.1"
